apiVersion: v1
kind: Service
metadata:
  name: ref-app-01-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ref-app-01
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}