apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx-custom
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}